/**
 * dbColumns — every column server.mjs names has to exist.
 *   node --import ./src/lib/_aliasLoader.mjs src/lib/dbColumns.test.mjs
 *
 * ─── The bug this exists to catch ───────────────────────────────────────────
 * `placeForecast` looked a student's balance up like this:
 *
 *     const { data: profile } = await supabaseAdmin
 *       .from("user_profiles").select("id, total_xp").eq("email", user.email)
 *
 * `user_profiles` HAS NO `email` COLUMN — the owner's address is `created_by`,
 * which migration 0001 says in its own comment and which the other 22 profile
 * lookups in the file all use. So PostgREST rejected the query, `profile` came
 * back null, `held` fell to its default of 0, and EVERY student was told "Not
 * enough XP to stake" regardless of their balance. The whole forecasting
 * feature was unusable and nothing anywhere said why.
 *
 * It passed lint, the build, the whole suite and a page-mount sweep, because
 * none of those touch a database. The only thing that would have caught it is
 * a student pressing the button — which is how it was found.
 *
 * ─── The schema is REAL, not parsed ─────────────────────────────────────────
 * `supabase/schema.json` is generated by applying every migration to an actual
 * Postgres 16 and reading `information_schema.columns` back
 * (`scripts/dumpSchema.sh`). A regex over the SQL would have to understand
 * `create table`, `alter table … add column`, `drop column`, renames and the
 * drop-and-recreate in 0008 — and a schema checker that is itself wrong about
 * the schema is worse than none. Regenerate it whenever a migration lands.
 *
 * ─── What it can and cannot see ─────────────────────────────────────────────
 * It reads the literal `.from("table")` … `.eq("column", …)` shape, which is
 * how nearly every query in the file is written. Dynamic table names, computed
 * column names and embedded PostgREST selects are skipped rather than guessed
 * at — a checker that cries wolf gets deleted, and the narrow version already
 * catches the bug that shipped.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

let passed = 0;
const check = (name, fn) => {
    try { fn(); passed += 1; console.log(`  ok  ${name}`); }
    catch (err) { console.error(`FAIL  ${name}\n      ${err.message}`); process.exitCode = 1; }
};

const schema = JSON.parse(readFileSync("supabase/schema.json", "utf8"));
const src = readFileSync("server.mjs", "utf8");

/**
 * Column references, as { table, column, kind, line }.
 *
 * A query is written as a chain, so the table is whichever `.from("x")` most
 * recently opened before the reference. Scanning forward from each `.from`
 * until the next one is exactly that, and it is why this needs no parser.
 */
export function columnRefs(text) {
    const refs = [];
    const fromRe = /\.from\(\s*"([a-z_][a-z0-9_]*)"\s*\)/g;
    const opens = [];
    let m;
    while ((m = fromRe.exec(text)) !== null) opens.push({ table: m[1], at: m.index });

    opens.forEach((open, i) => {
        // The chain runs to the next `.from(` or a little way ahead, whichever
        // comes first. Supabase chains are short; 1200 characters is generous
        // and stops one query's filters being read as the next one's.
        const end = Math.min(opens[i + 1]?.at ?? text.length, open.at + 1200);
        const chain = text.slice(open.at, end);

        // Filters: .eq / .neq / .gt / .gte / .lt / .lte / .like / .ilike / .in /
        // .contains / .is / .order — all take a column name first.
        const filterRe = /\.(eq|neq|gt|gte|lt|lte|like|ilike|in|is|order)\(\s*"([a-z_][a-z0-9_]*)"/g;
        let f;
        while ((f = filterRe.exec(chain)) !== null) {
            refs.push({
                table: open.table, column: f[2], kind: f[1],
                line: text.slice(0, open.at + f.index).split("\n").length,
            });
        }

        // select("a, b, c"). A template literal or an embedded resource
        // (`quiz:quizzes(...)`) is skipped rather than half-parsed.
        const selRe = /\.select\(\s*"([^"]*)"/g;
        let sel;
        while ((sel = selRe.exec(chain)) !== null) {
            const body = sel[1];
            if (body.includes("(") || body.includes(":") || body.trim() === "*") continue;
            body.split(",").map((c) => c.trim()).forEach((c) => {
                if (!/^[a-z_][a-z0-9_]*$/.test(c)) return;
                refs.push({
                    table: open.table, column: c, kind: "select",
                    line: text.slice(0, open.at + sel.index).split("\n").length,
                });
            });
        }
    });
    return refs;
}

check("the schema snapshot is real and complete", () => {
    assert.ok(Object.keys(schema).length > 40,
        `expected the app's tables, found ${Object.keys(schema).length}`);
    // The exact fact the bug turned on, asserted directly so a future reader
    // does not have to take the comment's word for it.
    assert.ok(schema.user_profiles.includes("created_by"));
    assert.ok(!schema.user_profiles.includes("email"),
        "user_profiles has no email column — that is the whole point of this file");
});

check("the scanner finds the references it is looking for", () => {
    // Without this the suite could pass by parsing nothing at all, which is
    // how a static check quietly stops working.
    const refs = columnRefs(src);
    assert.ok(refs.length > 200, `expected plenty of column references, found ${refs.length}`);
    assert.ok(refs.some((r) => r.table === "user_profiles" && r.column === "created_by"));
});

check("and it would have caught the bug that shipped", () => {
    const sample = `
        const { data } = await supabaseAdmin
          .from("user_profiles").select("id, total_xp").eq("email", user.email).single();`;
    const refs = columnRefs(sample);
    const bad = refs.filter((r) => !schema[r.table]?.includes(r.column));
    assert.equal(bad.length, 1);
    assert.equal(bad[0].column, "email");
});

check("EVERY COLUMN server.mjs NAMES EXISTS ON THE TABLE IT NAMES IT ON", () => {
    const problems = [];
    for (const ref of columnRefs(src)) {
        const cols = schema[ref.table];
        // A table this snapshot has never heard of is not a column problem —
        // it is a missing migration or a typo'd table, and saying "column x
        // does not exist on a table that does not exist" helps nobody.
        if (!cols) continue;
        if (!cols.includes(ref.column)) {
            problems.push(
                `server.mjs:${ref.line} — .${ref.kind}("${ref.column}") on "${ref.table}", `
                + `which has no such column. Did you mean one of: `
                + `${cols.filter((c) => c.includes(ref.column.slice(0, 4))
                    || ref.column.includes(c.slice(0, 4))).slice(0, 3).join(", ") || "—"}?`);
        }
    }
    assert.deepEqual(problems, [], `\n      ${problems.join("\n      ")}\n`);
});

check("every table server.mjs queries actually exists", () => {
    const unknown = [...new Set(columnRefs(src).map((r) => r.table))]
        .filter((t) => !schema[t]);
    assert.deepEqual(unknown, [],
        `\n      server.mjs queries tables with no migration: ${unknown.join(", ")}\n`);
});

console.log(`\n${passed} passed`);
