/**
 * Review — the audit. What the app thinks you owe it, and the means to argue.
 *
 * ─── The complaint this answers ─────────────────────────────────────────────
 * "The website always thinks a bunch of flashcards are due." It did, and it was
 * mostly wrong about it. A card is created with next_review_date set to today,
 * so a sixty-card deck generated by the AI tools reported sixty cards due
 * before anybody had opened one. And `next_review_date <= today` never stops
 * being true, so a fortnight off in exam block left every card permanently
 * overdue with the number only climbing. A count that only goes up is not
 * information. People stop reading it, and then they stop reading the numbers
 * next to it too.
 *
 * ─── What this page is ──────────────────────────────────────────────────────
 * Three things, in the order somebody actually needs them:
 *
 * 1. AN HONEST HEADLINE. The pile split into what it really is — genuinely due,
 *    never opened, and put away. Most students discover here that the terrifying
 *    number was ninety percent unopened material.
 *
 * 2. A DAY'S WORK. Not the backlog. Forty cards, with the rest reported
 *    underneath rather than hidden, because hiding it is how you get an app
 *    that lies pleasantly instead of one that lies alarmingly.
 *
 * 3. THE AUDIT ITSELF. Every pile, why it is claiming attention, and three
 *    ways to answer: review it, say you know it, or say not this week. Down to
 *    the individual card if somebody wants that.
 *
 * ─── Why "I know this" is not a delete ──────────────────────────────────────
 * The only existing exit from the queue was is_active: false. Somebody who
 * genuinely has a definition cold had to destroy the card to stop being asked,
 * which loses it for revision week. Marking known keeps the card, records when
 * the decision was made, and is one button to undo — so it is safe to use
 * casually, which is the only way an audit screen ever gets used at all.
 */
import React, { useState, useEffect, useMemo, useCallback } from "react";
import { motion } from "framer-motion";
import { Link, useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { createPageUrl } from "@/utils";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";
import { ToastAction } from "@/components/ui/toast";
import { Layers, Play, Sparkles, Inbox, ChevronDown } from "lucide-react";
import AuditPile from "@/components/study/AuditPile";
import HelpButton from "@/components/shared/HelpButton";
import {
    auditPiles, tally, dueQueue, todayISO,
    markKnown, markUnknown, snoozeFor,
} from "@/lib/due";
import { SECONDS_PER_CARD } from "@/lib/retention";

/** How long "not this week" actually is. */
const SNOOZE_DAYS = 7;

const minutesFor = (n) => Math.max(1, Math.round((n * SECONDS_PER_CARD) / 60));

/** One number and its caption, for the headline strip. */
function Figure({ value, label, tone = "text-foreground", hint }) {
    return (
        <div className="min-w-0">
            <p className={`font-display font-extrabold text-2xl sm:text-3xl leading-none ${tone}`}>{value}</p>
            <p className="stat-label mt-1">{label}</p>
            {hint && <p className="text-[11px] text-muted-foreground mt-0.5 leading-snug">{hint}</p>}
        </div>
    );
}

export default function Review() {
    const [cards, setCards] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [busy, setBusy] = useState(false);
    const [showKnown, setShowKnown] = useState(false);
    const { toast } = useToast();
    const navigate = useNavigate();

    // Computed once per render rather than per card, so a four-hundred-card
    // audit does not build four hundred Date objects to ask the same question.
    const today = todayISO();

    const load = useCallback(async () => {
        try {
            const user = await base44.auth.me();
            const rows = await base44.entities.Flashcard.filter({
                created_by: user.email, is_active: true,
            });
            setCards(rows || []);
        } catch (err) {
            console.error("Review load error:", err);
            toast({ title: "Couldn't load your cards", description: "Refresh and try again.", variant: "destructive" });
        } finally {
            setIsLoading(false);
        }
    }, [toast]);

    useEffect(() => { load(); }, [load]);

    const counts = useMemo(() => tally(cards, today), [cards, today]);
    const piles = useMemo(() => auditPiles(cards, today), [cards, today]);
    const queue = useMemo(() => dueQueue(cards, { today }), [cards, today]);

    /**
     * Apply a patch to a set of cards.
     *
     * Optimistic, because the whole point is that clearing a pile feels like
     * one gesture, and reversible from the toast, because a student marking
     * two hundred cards known should not have to be sure first. The previous
     * values are captured per card rather than assumed, so undo restores an
     * already-snoozed card to its snooze rather than to nothing.
     */
    const apply = useCallback(async (ids, patch, message) => {
        if (!ids?.length) return;
        const before = new Map();
        for (const c of cards) {
            if (!ids.includes(c.id)) continue;
            const prev = {};
            for (const k of Object.keys(patch)) prev[k] = c[k] ?? null;
            before.set(c.id, prev);
        }

        const write = async (idList, payload, perCard) => {
            setBusy(true);
            setCards((prev) => prev.map((c) => {
                if (!idList.includes(c.id)) return c;
                return { ...c, ...(perCard ? perCard.get(c.id) : payload) };
            }));
            try {
                if (perCard) {
                    // Undo can restore different values per card, so it groups
                    // by identical payload rather than sending one row at a time.
                    const groups = new Map();
                    for (const [id, p] of perCard) {
                        const key = JSON.stringify(p);
                        if (!groups.has(key)) groups.set(key, { payload: p, ids: [] });
                        groups.get(key).ids.push(id);
                    }
                    for (const g of groups.values()) await base44.entities.Flashcard.bulkUpdate(g.ids, g.payload);
                } else {
                    await base44.entities.Flashcard.bulkUpdate(idList, payload);
                }
            } catch (err) {
                console.error("Review update failed:", err);
                toast({ title: "That didn't save", description: "Your cards are unchanged.", variant: "destructive" });
                await load();
            } finally {
                setBusy(false);
            }
        };

        await write(ids, patch, null);
        toast({
            title: message,
            action: (
                <ToastAction altText="Undo" onClick={() => write(ids, null, before)}>Undo</ToastAction>
            ),
        });
    }, [cards, toast, load]);

    const onKnown = useCallback((ids, msg) => apply(ids, markKnown(), msg), [apply]);
    const onRestore = useCallback((ids, msg) => apply(ids, markUnknown(), msg), [apply]);
    const onSnooze = useCallback((ids, msg) => apply(ids, snoozeFor(SNOOZE_DAYS, today), msg), [apply, today]);

    const startReview = useCallback((pile) => {
        // Study owns the review session. The subject rides along so it opens on
        // the deck the student was just looking at rather than on the list.
        navigate(`${createPageUrl("Study")}?tab=spaced${pile ? `&subject=${encodeURIComponent(pile.subject)}` : ""}`);
    }, [navigate]);

    if (isLoading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="w-8 h-8 border-4 border-border border-t-primary rounded-full animate-spin" />
            </div>
        );
    }

    const active = piles.filter((p) => p.active > 0);
    const fresh = piles.filter((p) => p.active === 0 && p.fresh > 0);
    const known = piles.filter((p) => p.known > 0);
    const nothingAtAll = cards.length === 0;

    return (
        <div className="min-h-screen p-4 sm:p-6 lg:p-8">
            <div className="max-w-4xl mx-auto space-y-5">

                {/* ── HEADLINE ────────────────────────────────────────────── */}
                <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                    className="card-soft on-table p-5 lg:p-6">
                    <div className="flex items-start justify-between gap-3 mb-4">
                        <div>
                            <h1 className="font-display font-extrabold text-2xl text-foreground">Your review queue</h1>
                            <p className="text-sm text-muted-foreground mt-0.5">
                                Everything the app is keeping track of, and what it is actually asking of you.
                            </p>
                        </div>
                        <HelpButton page="Review" />
                    </div>

                    <div className="grid grid-cols-3 gap-4">
                        <Figure value={counts.active} label="Asking for you"
                            tone={counts.active > 0 ? "text-chart-3" : "text-muted-foreground"}
                            hint={counts.overdue > 0 ? `${counts.overdue} of them well past due` : null} />
                        <Figure value={counts.new} label="Never opened" tone="text-muted-foreground"
                            hint={counts.new > 0 ? "New material, not a backlog" : null} />
                        <Figure value={counts.known} label="Put away" tone="text-primary"
                            hint={counts.known > 0 ? "You said you know these" : null} />
                    </div>

                    {/* The reframe, said out loud. For most students this line is
                        the entire fix: the alarming number was never review debt. */}
                    {counts.new > counts.active && counts.new > 0 && (
                        <p className="mt-4 text-sm text-muted-foreground border-t border-border pt-3">
                            Most of your queue is material you have not started yet. That is not you falling
                            behind, and nothing here is counting it against you.
                        </p>
                    )}
                </motion.div>

                {/* ── A DAY'S WORK ────────────────────────────────────────── */}
                {queue.queue.length > 0 && (
                    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.04 }}
                        className="rounded-2xl bg-primary/5 border border-primary/15 on-table p-5 lg:p-6">
                        <div className="flex flex-col sm:flex-row sm:items-center gap-4">
                            <div className="flex items-center gap-3 flex-1 min-w-0">
                                <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
                                    <Layers className="w-5 h-5 text-primary" />
                                </div>
                                <div className="min-w-0">
                                    <h2 className="font-display font-extrabold text-foreground">
                                        {queue.queue.length} card{queue.queue.length === 1 ? "" : "s"} for today
                                    </h2>
                                    <p className="text-sm text-muted-foreground">
                                        About {minutesFor(queue.queue.length)} minutes.
                                        {queue.backlog > 0
                                            ? ` ${queue.backlog} more behind them, and they will wait.`
                                            : " That is the lot."}
                                    </p>
                                </div>
                            </div>
                            <Button onClick={() => startReview(null)} className="rounded-xl gap-2 flex-shrink-0">
                                <Play className="w-4 h-4" /> Start
                            </Button>
                        </div>
                    </motion.div>
                )}

                {/* ── THE AUDIT ───────────────────────────────────────────── */}
                {nothingAtAll ? (
                    <div className="card-soft on-table p-10 text-center">
                        <Inbox className="w-10 h-10 text-muted-foreground/40 mx-auto mb-3" />
                        <h2 className="font-display font-extrabold text-foreground">No cards yet</h2>
                        <p className="text-sm text-muted-foreground mt-1 mb-4">
                            Once you have made some, this is where you check what the app is asking of you.
                        </p>
                        <Link to={createPageUrl("Study")}>
                            <Button className="rounded-xl gap-2"><Sparkles className="w-4 h-4" /> Make some cards</Button>
                        </Link>
                    </div>
                ) : (
                    <>
                        {active.length > 0 && (
                            <section className="space-y-3">
                                <h2 className="stat-label px-1">Claiming your attention</h2>
                                {active.map((p) => (
                                    <AuditPile key={p.subject} pile={p} today={today} busy={busy}
                                        onKnown={onKnown} onSnooze={onSnooze} onRestore={onRestore}
                                        onReview={startReview} />
                                ))}
                            </section>
                        )}

                        {active.length === 0 && counts.active === 0 && (
                            <div className="card-soft on-table p-8 text-center">
                                <h2 className="font-display font-extrabold text-foreground">Nothing is due</h2>
                                <p className="text-sm text-muted-foreground mt-1">
                                    {counts.new > 0
                                        ? `You have ${counts.new} card${counts.new === 1 ? "" : "s"} waiting to be started, whenever you want them.`
                                        : "Everything is scheduled ahead. Come back when something comes up."}
                                </p>
                            </div>
                        )}

                        {fresh.length > 0 && (
                            <section className="space-y-3">
                                <h2 className="stat-label px-1">Not started yet</h2>
                                <p className="text-xs text-muted-foreground px-1 -mt-1">
                                    These have never been reviewed, so nothing here is overdue. They join the
                                    queue a few at a time once your due pile is clear.
                                </p>
                                {fresh.map((p) => (
                                    <AuditPile key={p.subject} pile={p} today={today} busy={busy}
                                        onKnown={onKnown} onSnooze={onSnooze} onRestore={onRestore}
                                        onReview={startReview} />
                                ))}
                            </section>
                        )}

                        {known.length > 0 && (
                            <section className="space-y-3">
                                <button type="button" onClick={() => setShowKnown((v) => !v)}
                                    aria-expanded={showKnown}
                                    className="flex items-center gap-2 stat-label px-1 hover:text-foreground">
                                    Put away ({counts.known})
                                    <ChevronDown className={`w-3.5 h-3.5 transition-transform ${showKnown ? "rotate-180" : ""}`} />
                                </button>
                                {showKnown && (
                                    <>
                                        <p className="text-xs text-muted-foreground px-1 -mt-1">
                                            Cards you have said you know. They are still yours, still in the deck,
                                            and one button away from coming back.
                                        </p>
                                        {known.map((p) => (
                                            <AuditPile key={p.subject} pile={p} today={today} busy={busy}
                                                onKnown={onKnown} onSnooze={onSnooze} onRestore={onRestore}
                                                onReview={null} />
                                        ))}
                                    </>
                                )}
                            </section>
                        )}
                    </>
                )}
            </div>
        </div>
    );
}
